name: ml_is
channels:
  - conda-forge
  - ska
dependencies:
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter_client
  - jupyter_contrib_nbextensions
  - matplotlib
  - nltk
  - pandas
  - pygtk
  - python=3.6
  - scikit-learn
  - seaborn
